# docker-compose.yml for local development

version: '3.8'

services:
  db:
    image: postgres:15-alpine # Use a specific version
    container_name: pmdc_db_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Persist data
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432 to avoid conflicts
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-pmdc} # Default user if not set in .env
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme} # Default password if not set in .env
      - POSTGRES_DB=${POSTGRES_DB:-pmdc_dev} # Default database if not set in .env
    networks:
      - pmdc_network

  # Optional: Add Redis service if using Celery with Redis backend/broker
  redis:
    image: redis:7-alpine
    container_name: pmdc_redis_dev
    ports:
      - "6379:6379"
    networks:
      - pmdc_network

  # Optional: Add the FastAPI app service (builds from Dockerfile)
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: pmdc_api_dev
  #   volumes:
  #     - ./app:/app/app # Mount app code for hot-reloading
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #     - redis # Add if using redis
  #   environment:
  #     - DATABASE_URI=postgresql+psycopg://${POSTGRES_USER:-pmdc}:${POSTGRES_PASSWORD:-changeme}@db:5432/${POSTGRES_DB:-pmdc_dev}
  #     - CELERY_BROKER_URL=redis://redis:6379/0 # Add if using redis
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0 # Add if using redis
  #     # Add other necessary environment variables (SaaS keys, Auth settings) via .env file or directly
  #   env_file:
  #     - .env
  #   networks:
  #     - pmdc_network
  #   # Command to run the app with hot-reloading (example)
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: # Define the named volume for persistence

networks:
  pmdc_network:
    driver: bridge 